# -*- coding: utf-8 -*-
"""Autos_Usados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1je-Q5OvTuzz1R9QlBdz4TicSvASw-LVh
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("used_cars.csv")
df.head()

import pandas as pd

df['price'] = df['price'].str.replace('$','').str.replace(',','').astype(float)

y = pd.qcut(df['price'], 3, labels=['Económico','Medio','Premium'])
y.value_counts()

# --- LIMPIEZA DE MILAGE ---
df['milage'] = df['milage'].astype(str)  # Forzar a string
df['milage'] = df['milage'].str.replace(' mi.','', regex=False).str.replace(',','', regex=False)
df['milage'] = pd.to_numeric(df['milage'], errors='coerce')  # Convertir a número

# --- LIMPIEZA DE PRICE ---
df['price'] = df['price'].astype(str)  # Forzar a string
df['price'] = df['price'].str.replace('$','', regex=False).str.replace(',','', regex=False)
df['price'] = pd.to_numeric(df['price'], errors='coerce')  # Convertir a número

# Revisar resultados
df[['milage','price']].head()

print(df.isnull().sum())

for col in df.columns:
    if df[col].dtype == 'float64':
        df[col].fillna(df[col].median(), inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)

df.drop_duplicates(inplace=True)

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['brand','model','fuel_type','transmission','ext_col','int_col']
encoder = LabelEncoder()
for col in categorical_cols:
    df[col] = encoder.fit_transform(df[col].astype(str))

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['milage','model_year','price']] = scaler.fit_transform(df[['milage','model_year','price']])

def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

df = remove_outliers(df, "price")
df = remove_outliers(df, "milage")

Q1, Q3 = df['price'].quantile([0.25,0.75])
IQR = Q3 - Q1
df = df[(df['price'] >= Q1 - 1.5*IQR) & (df['price'] <= Q3 + 1.5*IQR)]

from sklearn.model_selection import train_test_split

X = df.drop('price', axis=1)
y = pd.qcut(df['price'], 3, labels=['Económico','Medio','Premium'])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

!pip install kagglehub pandas matplotlib seaborn scikit-learn --quiet

import kagglehub
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

path = kagglehub.dataset_download("taeefnajib/used-car-price-prediction-dataset")
print("Ruta del dataset:", path)

df = pd.read_csv(f"{path}/used_cars.csv")
df.columns = ['brand', 'model', 'model_year', 'milage', 'fuel_type',
              'engine', 'transmission', 'ext_col', 'int_col',
              'accident', 'clean_title', 'price']

df['price'] = df['price'].replace(r'[\$,]', '', regex=True).astype(float)
df['milage'] = df['milage'].replace(r'[,.a-zA-Z\s\.]', '', regex=True).astype(float)
df['model_year'] = df['model_year'].astype(int)

df = df.dropna(subset=['brand', 'model_year', 'milage', 'fuel_type', 'price'])

p33 = df['price'].quantile(0.33)
p66 = df['price'].quantile(0.66)

def clasificar_precio(valor):
    if valor <= p33:
        return 'Económico'
    elif valor <= p66:
        return 'Medio'
    else:
        return 'Premium'

df['rango_precio'] = df['price'].apply(clasificar_precio)

features = ['model_year', 'milage', 'fuel_type', 'transmission', 'brand']
target = 'rango_precio'

le = LabelEncoder()
for col in ['fuel_type', 'transmission', 'brand']:
    df[col] = le.fit_transform(df[col].astype(str))

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Entrenamiento: {X_train.shape[0]} registros")
print(f"Prueba: {X_test.shape[0]} registros")

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print("\n🔍 RESULTADOS DEL MODELO RANDOM FOREST")
print(f"Exactitud (Accuracy): {acc*100:.2f}%\n")

print("📄 Reporte de clasificación:")
print(classification_report(y_test, y_pred))

plt.figure(figsize=(6,4))
sns.heatmap(
    confusion_matrix(y_test, y_pred),
    annot=True, fmt='d', cmap='Blues',
    xticklabels=['Económico','Medio','Premium'],
    yticklabels=['Económico','Medio','Premium']
)
plt.title('Matriz de Confusión - Random Forest')
plt.xlabel('Predicción')
plt.ylabel('Real')
plt.show()

importances = rf.feature_importances_
plt.barh(features, importances)
plt.title("Importancia de las Variables - Random Forest")
plt.xlabel("Importancia relativa")
plt.show()

!pip install kagglehub pandas matplotlib seaborn scikit-learn --quiet

import kagglehub
path = kagglehub.dataset_download("taeefnajib/used-car-price-prediction-dataset")

import pandas as pd
df = pd.read_csv(f"{path}/used_cars.csv")

df.columns = ['brand','model','model_year','milage','fuel_type','engine','transmission','ext_col','int_col','accident','clean_title','price']
df['price'] = df['price'].replace(r'[\$,]', '', regex=True).astype(float)
df['milage'] = df['milage'].replace(r'[,.a-zA-Z\s]', '', regex=True).astype(float)
df = df.dropna(subset=['brand','model_year','milage','fuel_type','price'])

import numpy as np
p33, p66 = np.percentile(df["price"], [33, 66])

def label_price(v):
    if v <= p33: return "Económico"
    elif v <= p66: return "Medio"
    else: return "Premium"

df["price_range"] = df["price"].apply(label_price)

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
for col in ['brand','fuel_type','transmission']:
    df[col] = le.fit_transform(df[col])

X = df[['model_year','milage','brand','fuel_type','transmission']]
y = df['price_range']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42, stratify=y)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt="d", cmap="Blues",
            xticklabels=["Económico","Medio","Premium"],
            yticklabels=["Económico","Medio","Premium"])
plt.title("Matriz de Confusión - Random Forest")
plt.show()

# Guardar un encoder por columna
encoders = {}
for col in ['brand','fuel_type','transmission']:
    enc = LabelEncoder()
    df[col] = enc.fit_transform(df[col])
    encoders[col] = enc

def predecir_auto(model_year, milage, brand, fuel_type, transmission):
    # Convertir valores categóricos usando los encoders guardados
    brand_enc = encoders['brand'].transform([brand])[0]
    fuel_enc = encoders['fuel_type'].transform([fuel_type])[0]
    trans_enc = encoders['transmission'].transform([transmission])[0]

    # Crear DataFrame con los valores ingresados
    entrada_df = pd.DataFrame([{
        "model_year": model_year,
        "milage": milage,
        "brand": brand_enc,
        "fuel_type": fuel_enc,
        "transmission": trans_enc
    }])

    # Realizar predicción
    pred = rf.predict(entrada_df)[0]
    return pred

encoders = {}
for col in ['brand','fuel_type','transmission']:
    enc = LabelEncoder()
    df[col] = enc.fit_transform(df[col].astype(str))
    encoders[col] = enc

def predecir_auto(model_year, milage, brand, fuel_type, transmission):
    # Validar si las categorías existen en el encoder
    for col, value in zip(['brand','fuel_type','transmission'],
                          [brand, fuel_type, transmission]):
        if value not in encoders[col].classes_:
            return f"⚠ Error: '{value}' no existe en el dataset para '{col}'. Valores válidos: {list(encoders[col].classes_)[:10]} ..."

    # Codificar
    brand_enc = encoders['brand'].transform([brand])[0]
    fuel_enc = encoders['fuel_type'].transform([fuel_type])[0]
    trans_enc = encoders['transmission'].transform([transmission])[0]

    entrada = pd.DataFrame([{
        'model_year': model_year,
        'milage': milage,
        'brand': brand_enc,
        'fuel_type': fuel_enc,
        'transmission': trans_enc
    }])

    pred = rf.predict(entrada)[0]
    return f"✅ Clasificación: {pred}"

predecir_auto(
    model_year=2018,
    milage=60000,
    brand="0",
    fuel_type="1",
    transmission="10"
)

sorted(encoders['brand'].classes_)[:30]

df = pd.read_csv(f"{path}/used_cars.csv")

df.columns = ['brand','model','model_year','milage','fuel_type','engine','transmission','ext_col','int_col','accident','clean_title','price']
df['price'] = df['price'].replace(r'[\$,]', '', regex=True).astype(float)
df['milage'] = df['milage'].replace(r'[,.a-zA-Z\s]', '', regex=True).astype(float)

df = df.dropna(subset=['brand','model_year','milage','fuel_type','price'])

from sklearn.preprocessing import LabelEncoder

encoders = {}
for col in ['brand','fuel_type','transmission']:
    enc = LabelEncoder()
    df[col] = df[col].astype(str)
    df[col] = enc.fit_transform(df[col])
    encoders[col] = enc

print(sorted(encoders['brand'].classes_)[:30])
print(encoders['fuel_type'].classes_)
print(encoders['transmission'].classes_)

def predecir_auto(model_year, milage, brand, fuel_type, transmission):
    for col, value in zip(['brand','fuel_type','transmission'],
                          [brand, fuel_type, transmission]):
        if value not in encoders[col].classes_:
            return f"⚠ '{value}' no existe en '{col}'. Valores válidos: {list(encoders[col].classes_)[:10]} ..."

    brand_enc = encoders['brand'].transform([brand])[0]
    fuel_enc = encoders['fuel_type'].transform([fuel_type])[0]
    trans_enc = encoders['transmission'].transform([transmission])[0]

    df_input = pd.DataFrame([{
        "model_year": model_year,
        "milage": milage,
        "brand": brand_enc,
        "fuel_type": fuel_enc,
        "transmission": trans_enc
    }])

    pred = rf.predict(df_input)[0]
    return f"✅ Clasificación: {pred}"

predecir_auto(
    model_year=2018,
    milage=60000,
    brand="Toyota",
    fuel_type="Gasoline",
    transmission="Automatic"
)

predecir_auto(
    model_year=2008,
    milage=190000,
    brand="Chevrolet",
    fuel_type="Gasoline",
    transmission="Manual"
)

predecir_auto(
    model_year=2022,
    milage=12000,
    brand="BMW",
    fuel_type="Gasoline",
    transmission="Automatic"
)
